theme: jekyll-theme-midnight
title: Mihir Mehta
description: I am a passionate software engineer. I love solving complex problems and working with smart people. I am curious about computer technology and am currently exploring private blockchains. My aim is to deliver high-impact projects which can be used by millions of people worldwide.<br>Figuring It Out.
