theme: jekyll-theme-midnight
title: Mihir Mehta
description: I am a passionate full-stack software engineer who loves solving fun problems and working with smart people. I am curios about different stuff and aim to deliver high-impact projects which I can proudly present to the dev community. I have experience working with private blockchains <br> I am yet Figuring It Out.
